import {
	FunctionTestData,
	describeAndTestFunction,
} from '#/helpers/test-function';

import Util from '@/content/util';

const YT_DESCRIPTION_EXAMPLE_1 = `Provided to YouTube by IDOL

Tranquility (Forces of Nature Remix) · Aquasky

Shadow Era, Pt. 2

℗ Passenger Ltd

Released on: 2015-10-09

Lyricist: B. Newitt
Lyricist: D. Wallace
Lyricist: K. Bailey
Composer: B. Newitt
Composer: D. Wallace
Composer: K. Bailey

Auto-generated by YouTube.`;

const YT_DESCRIPTION_EXAMPLE_2 = `Capoeira (Airbase pres. Scarab Remix) · Under Sun

Capoeira

℗ Armada Music B.V.

Released on: 2006-08-21

A R T I S T: Under Sun

Auto-generated by YouTube.`;

const YT_DESCRIPTION_EXAMPLE_3 = `Provided to YouTube by The Orchard Enterprises

Fugitive · Time, The Valuator · Mattéo Gelsomino

How Fleeting, How Fragile

℗ 2018 Long Branch Records

Released on: 2018-08-03

Auto-generated by YouTube.`;

const YT_DESCRIPTION_EXAMPLE_4 = `Provided to YouTube by The Orchard Enterprises

Fugitive

How Fleeting, How Fragile

Auto-generated by YouTube.`;

const functionTestData: FunctionTestData<
	typeof Util.parseYtVideoDescription
>[] = [
	{
		description: 'should not parse null description',
		funcParameters: [null],
		expectedValue: null,
	},
	{
		description: 'should parse normal description',
		funcParameters: [YT_DESCRIPTION_EXAMPLE_1],
		expectedValue: {
			album: 'Shadow Era, Pt. 2',
			track: 'Tranquility (Forces of Nature Remix)',
			artist: 'Aquasky',
		},
	},
	{
		description: 'should parse description w/o "Autogenerated" header',
		funcParameters: [YT_DESCRIPTION_EXAMPLE_2],
		expectedValue: {
			album: 'Capoeira',
			track: 'Capoeira (Airbase pres. Scarab Remix)',
			artist: 'Under Sun',
		},
	},
	{
		description: 'should parse description w/ featuring artists',
		funcParameters: [YT_DESCRIPTION_EXAMPLE_3],
		expectedValue: {
			album: 'How Fleeting, How Fragile',
			track: 'Fugitive (feat. Mattéo Gelsomino)',
			artist: 'Time, The Valuator',
		},
	},
	{
		description: 'should parse description w/o artist',
		funcParameters: [YT_DESCRIPTION_EXAMPLE_4],
		expectedValue: {
			album: 'How Fleeting, How Fragile',
			track: 'Fugitive',
			artist: null,
		},
	},
];

describeAndTestFunction(
	Util.parseYtVideoDescription.bind(Util),
	functionTestData
);
