name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Added'
    label: 'added'
  - title: '⬆️ Updated'
    label: 'updated'
  - title: '🐛 Fixed'
    label: 'fixed'
  - title: '🔧 Maintenance'
    label: 'maintenance'
exclude-labels:
  - 'skip-changelog'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES
