name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🎁 New features'
    when:
      - labels: ['new-feature']
  - title: '🐛 Core fixes'
    when:
      - labels: ['core-fix']
  - title: '🚀 New connectors'
    when:
      - labels: ['new-connector']
  - title: '🐛 Fixed connectors'
    when:
      - labels: ['fixed-connector']
  - title: '⬆️ Updated'
    when:
      - labels: ['updated']
  - title: '🔧 Maintenance'
    when:
      - labels: ['maintenance']
  - type: 'pre-exclude'
    when:
      - labels: ['skip-changelog', 'chore']
  - type: 'version-resolver'
    semver-increment: 'major'
    when:
      - labels: ['major-change']
  - type: 'version-resolver'
    semver-increment: 'minor'
    when:
      - labels: ['minor-change']
  - type: 'version-resolver'
    semver-increment: 'patch'
    when:
      - labels: ['patch-change']
version-resolver:
  default: patch
template: |
  $CHANGES
