categories:
  - title: '🚀 Added'
    label: 'added'
  - title: '⬆️ Updated'
    label: 'updated'
  - title: '🐛 Fixed'
    label: 'fixed'
<<<<<<< Updated upstream
  - title: '🔧 Maintenance'
    label: 'maintenance'
=======
exclude-labels:
  - 'skip-changelog'
>>>>>>> Stashed changes
template: |
  ## Changes

  $CHANGES
