plugins:
  - solid
  - '@typescript-eslint/eslint-plugin'
  - eslint-plugin-tsdoc
  - react
extends:
  - eslint:recommended
  - plugin:solid/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  project: ./tsconfig.json
  tsconfigRootDir: .
  ecmaVersion: 2018
  sourceType: module
rules:
  tsdoc/syntax: warn
  react/react-in-jsx-scope: off
  react/no-unknown-property: off
  react/jsx-key: off
  no-mixed-spaces-and-tabs:
    - error
    - smart-tabs
  '@typescript-eslint/ban-ts-comment': off
  prefer-const:
    - error
    - destructuring: all
