import type { ArtistTrackInfo, BaseState } from '@/core/types';

export {};

/**
 * Quick links to debug and test the connector:
 *
 * https://www.youtube.com/watch?v=WA3hL4hDx9c - auto-generated music video
 * The connector should get info via `getTrackInfoFromDescription` function
 *
 * https://www.youtube.com/watch?v=eYLbteOm42k - video with chapters available
 * The connector should get info via `getTrackInfoFromChapters` function
 *
 * https://www.youtube.com/watch?v=mHnC_vELJsk - regular video
 * The connector should get info via `getTrackInfoFromTitle` function
 */

/**
 * CSS selector of video element. It's common for both players.
 */
const videoSelector = '.html5-main-video';

const videoPlayerSelector = '.html5-video-player';
const chapterNameSelector = '.html5-video-player .ytp-chapter-title-content';
const videoTitleSelector = [
	'.html5-video-player .ytp-title-link',
	'.slim-video-information-title .yt-core-attributed-string',
];
const channelNameSelector = [
	'#top-row .ytd-channel-name a',
	'.slim-owner-channel-name .yt-core-attributed-string',
];
const videoDescriptionSelector = [
	'#description.ytd-expandable-video-description-body-renderer',
	'#meta-contents #description',
	'.crawler-full-description',
];
enum Category {
	// Dummy category indicates an actual category is being fetched
	Pending = 'YT_DUMMY_CATEGORY_PENDING',
	// Fallback value in case when we cannot fetch a category.
	Unknown = 'YT_DUMMY_CATEGORY_UNKNOWN',
	Music = 'Music',
	Entertainment = 'Entertainment',
}

/**
 * Array of categories allowed to be scrobbled.
 */
const allowedCategories: string[] = [];

/**
 * Wether we should only scrobble music recognised by YouTube Music
 */
let scrobbleMusicRecognisedOnly = false;

/**
 * Wether the Youtube Music track info getter is enabled
 */
let ytMusicEnabled = false;
/**
 * Wether the Youtube Watch track info getter is enabled
 */
let ytWatchEnabled = false;
/**
 * Wether the Youtube Account track info getter is enabled
 */
let ytChannelEnabled = false;

/**
 * Wether we should only use attributed songs if Auto-generated
 */
let useAttributedOnlyForAutoGenerated = false;

type CacheValue<T> =
	| { done: false }
	| ({ done: true } & (T | { error: string }))
	| undefined;

type YoutubeChannelInfo = {
	musicArtistName: string | null;
};
/**
 * caches results of https://youtube.com/channel/${channelId} requests
 */
const youtubeChannelCache: {
	[channelId: string]: CacheValue<YoutubeChannelInfo>;
} = {};

type YoutubeWatchInfo = {
	category: string;
	title: string;
	channel: string;

	channelId: string;
	attributedTrackInfo?: {
		trackArt?: string;
		track?: string;
		artist?: string;
		album?: string;
	};

	chapters: {
		title: string;
		time: number;
	}[];
};
/**
 * caches results of https://youtube.com/watch?v=${videoId} requests
 */
const youtubeWatchCache: {
	[videoId: string]: CacheValue<YoutubeWatchInfo>;
} = {};

type YoutubeMusicInfo = {
	recognisedByYtMusic: boolean;
	currentTrackInfo: { artist?: string; track?: string };
};
/**
 * caches results of https://music.youtube.com/youtubei/v1/player requests
 */
const youtubeMusicCache: {
	[videoId: string]: CacheValue<YoutubeMusicInfo>;
} = {};

const trackInfoGetters: (() =>
	| BaseState
	| null
	| undefined
	| Record<string, never>)[] = [
	getTrackInfoFromYoutubeFetch,
	// getTrackInfoFromChapters,
	// getTrackInfoFromYoutubeMusic,
	// getTrackInfoFromTitle,
];

readConnectorOptions();
setupEventListener();

Connector.playerSelector = ['#content', '#player'];

Connector.scrobbleInfoLocationSelector = '#primary #title.ytd-watch-metadata';
Connector.scrobbleInfoStyle = {
	...Connector.scrobbleInfoStyle,
	fontSize: '1.17em',
	fontWeight: '700',
};

Connector.loveButtonSelector =
	'ytd-watch-metadata like-button-view-model button[aria-pressed="false"]';

Connector.unloveButtonSelector =
	'ytd-watch-metadata like-button-view-model button[aria-pressed="true"]';

Connector.getChannelId = () =>
	new URL(
		(
			Util.queryElements([
				'#upload-info .ytd-channel-name .yt-simple-endpoint',
				'.slim-owner-icon-and-title',
			]) as NodeListOf<HTMLAnchorElement>
		)?.[0]?.href ?? 'https://youtube.com/',
	).pathname.slice(1);

Connector.channelLabelSelector = [
	'#primary #title+#top-row ytd-channel-name .yt-formatted-string',
	'.slim-owner-icon-and-title .yt-core-attributed-string',
];

Connector.getTrackInfo = () => {
	const trackInfo: BaseState = {};

	for (const getter of trackInfoGetters) {
		const currentTrackInfo = getter();
		if (!currentTrackInfo) {
			continue;
		}

		if (!trackInfo.artist) {
			trackInfo.artist = currentTrackInfo.artist;
		}

		if (!trackInfo.trackArt) {
			trackInfo.trackArt = currentTrackInfo.trackArt;
		}

		if (!trackInfo.track) {
			trackInfo.track = currentTrackInfo.track;
		}

		if (!trackInfo.album && 'album' in currentTrackInfo) {
			trackInfo.album = currentTrackInfo.album;
		}

		if (!Util.isArtistTrackEmpty(trackInfo)) {
			break;
		}
	}

	return trackInfo;
};

Connector.getTimeInfo = () => {
	const videoElement = document.querySelector(
		videoSelector,
	) as HTMLVideoElement;
	if (videoElement && !areChaptersAvailable()) {
		let { currentTime, duration, playbackRate } = videoElement;

		currentTime /= playbackRate;
		duration /= playbackRate;

		return { currentTime, duration };
	}

	return null;
};

Connector.isPlaying = () => {
	return Util.hasElementClass(videoPlayerSelector, 'playing-mode');
};

Connector.getOriginUrl = () => {
	const videoId = getVideoId();

	return `https://youtu.be/${videoId}`;
};

Connector.getUniqueID = () => {
	if (areChaptersAvailable()) {
		return null;
	}

	return getVideoId();
};

Connector.scrobblingDisallowedReason = () => {
	if (document.querySelector('.ad-showing')) {
		return 'IsAd';
	}

	// Workaround to prevent scrobbling the video opened in a background tab.
	if (!isVideoStartedPlaying()) {
		return 'Other';
	}

	if (scrobbleMusicRecognisedOnly) {
		const videoId = getVideoId();

		const ytMusicResponse = fetchYoutubeMusic(videoId);

		if (!ytMusicResponse) {
			return 'Other';
		}

		if (!ytMusicResponse.done) {
			// not done loading yet
			return 'IsLoading';
		}

		if (!ytMusicResponse.recognisedByYtMusic) {
			// not recognised!
			return 'NotOnYouTubeMusic';
		}
	}

	return isVideoCategoryAllowed() ? null : 'ForbiddenYouTubeCategory';
};

Connector.isStateChangeAllowed = () => {
	// const videoId = getVideoId();
	// if (!videoId) {
	// 	return false;
	// }

	// wait for requests to finish
	// const ytMusicCache = youtubeMusicCache[videoId];
	// if (ytMusicCache && !ytMusicCache.done) {
	// 	return false;
	// }
	// const ytWatchCache = youtubeWatchCache[videoId];
	// if (ytWatchCache && !ytWatchCache.done) {
	// 	return false;
	// }
	// const ytChannelCache = youtubeChannelCache[videoId];
	// if (ytChannelCache && !ytChannelCache.done) {
	// 	return false;
	// }

	// const ytFetchResponse = fetchYoutubeMusic(videoId);
	// const ytWatchResponse = fetchYoutubeWatch(videoId);
	// const ytChannelResponse = fetchYoutubeChannel(
	// 	ytWatchResponse?.done ? ytWatchResponse.channelId : null,
	// );
	// if (
	// 	!(!ytFetchResponse || ytFetchResponse.done) ||
	// 	!(!ytWatchResponse || ytWatchResponse.done) ||
	// 	!(!ytChannelResponse || ytChannelResponse.done)
	// ) {
	// 	// wait for requests to finish
	// 	return false;
	// }
	return true;
};

Connector.applyFilter(
	MetadataFilter.createYouTubeFilter().append({
		artist: [removeLtrRtlChars, removeNumericPrefix],
		track: [removeLtrRtlChars, removeNumericPrefix],
	}),
);

function setupEventListener() {
	document
		.querySelector(videoSelector)
		?.addEventListener('timeupdate', Connector.onStateChanged);
}

function areChaptersAvailable() {
	const text = Util.getTextFromSelectors(chapterNameSelector);

	// SponsorBlock extension hijacks chapter element. Ignore it.
	if (
		document.querySelector(
			'.ytp-chapter-title-content.sponsorBlock-segment-title',
		)
	) {
		return false;
	}

	if (text) {
		// YouTube introduced putting text into the current chapter element for
		// referring users to the timeline ("In this video"). hard to check for
		// because that text gets translated, we can however check if the
		// description has a chapter like that, if not it's not a real chapter
		if (
			!document.querySelector(
				`.ytd-watch-metadata ytd-macro-markers-list-item-renderer #details:has([title="${CSS.escape(text)}"]):has(#time)`,
			)
		) {
			return false;
		}
	}

	// Return the text if no sponsorblock text.
	return text;
}

type VideoData = {
	video_id?: string;
	title?: string;
	author?: string;
};
function getVideoData(): VideoData | null {
	return null;
	return (
		(
			document.querySelector('.html5-video-player') as any
		)?.getVideoData() ?? null
	);
}

function getVideoId() {
	const videoData = getVideoData();
	if (videoData?.video_id) {
		return videoData.video_id;
	}

	/*
	 * ytd-watch-flexy element contains ID of a first played video
	 * if the miniplayer is visible, so we should check
	 * if URL of a current video in miniplayer is accessible.
	 */
	const miniPlayerVideoUrl = Util.getAttrFromSelectors(
		'ytd-miniplayer[active] [selected] a',
		'href',
	);
	if (miniPlayerVideoUrl) {
		return Util.getYtVideoIdFromUrl(miniPlayerVideoUrl);
	}

	const videoIDDesktop = Util.getAttrFromSelectors(
		'ytd-watch-flexy',
		'video-id',
	);
	if (videoIDDesktop) {
		return videoIDDesktop;
	}

	// as a fallback on mobile, try to get the video ID from the URL
	const videoIDMobile = new URLSearchParams(window.location.search).get('v');
	return videoIDMobile;
}

function getVideoCategory() {
	const videoId = getVideoId();

	if (!videoId) {
		return null;
	}

	const ytWatchResponse = fetchYoutubeWatch(videoId);

	if (!ytWatchResponse) {
		return Category.Unknown;
	}

	if (!ytWatchResponse.done) {
		return Category.Pending;
	}

	return ytWatchResponse.category;
}

const textJsonUtils = {
	findJson: (data: string, prefix: string) => {
		const start = data.indexOf(prefix) + prefix.length;
		const len = data.slice(start).search(/(?!\\)(\}|\])(?:\s*;)/) + 1;
		return JSON.parse(data.substring(start, start + len));
	},
	getPaths: (obj: any | undefined, path: string | string[]) => {
		if (!obj) return {};
		let paths: { [_: string]: any } = {};
		for (let p of typeof path === 'string' ? [path] : path) {
			let ps: { [_: string]: any } = { '': obj };
			for (const segm of p.split(/\.|\[\]/)) {
				let new_paths: { [_: string]: any } = {};
				if (segm.length == 0) {
					for (const [path, obj] of Object.entries(ps)) {
						if (!Array.isArray(obj)) continue;
						for (let i = 0; i < obj.length; i++) {
							new_paths[path + '[' + i + ']'] = obj[i];
						}
					}
					p = p.substring(2);
				} else {
					for (const [path, obj] of Object.entries(ps)) {
						if (segm in obj) {
							new_paths[path + '.' + segm] = obj[segm];
						}
					}
				}
				ps = new_paths;
			}
			paths = { ...paths, ...ps };
		}
		return paths;
	},
	getAll: (obj: any | undefined, path: string | string[]) => {
		const paths = textJsonUtils.getPaths(obj, path);
		return Object.values(paths);
	},
	getFirst: (obj: any | undefined, path: string | string[]) => {
		return textJsonUtils.getAll(obj, path).at(0);
	},
	getIf: (
		obj: any | undefined,
		path: string | string[],
		predicate: (obj: any) => boolean,
	) => {
		return textJsonUtils.getAll(obj, path).find(predicate);
	},
};

/**
 * Asynchronously read connector options.
 */
async function readConnectorOptions() {
	if (await Util.getOption('YouTube', 'scrobbleMusicOnly')) {
		allowedCategories.push(Category.Music);
	}
	if (await Util.getOption('YouTube', 'scrobbleEntertainmentOnly')) {
		allowedCategories.push(Category.Entertainment);
	}
	Util.debugLog(`Allowed categories: ${allowedCategories.join(', ')}`);

	if (await Util.getOption('YouTube', 'scrobbleMusicRecognisedOnly')) {
		scrobbleMusicRecognisedOnly = true;
		Util.debugLog('Only scrobbling when recognised by YouTube Music');
	}

	if (await Util.getOption('YouTube', 'enableGetTrackInfoFromYtMusic')) {
		ytMusicEnabled = true;
		Util.debugLog('Get track info from YouTube Music enabled');
	}
	if (await Util.getOption('YouTube', 'enableGetTrackInfoFromYtWatch')) {
		ytWatchEnabled = true;
		Util.debugLog('Get track info from YouTube Watch enabled');
	}
	if (await Util.getOption('YouTube', 'enableGetTrackInfoFromYtChannel')) {
		ytChannelEnabled = true;
		Util.debugLog('Get track info from YouTube Channel enabled');
	}
	if (await Util.getOption('YouTube', 'useAttributedOnlyForAutoGenerated')) {
		useAttributedOnlyForAutoGenerated = true;
		Util.debugLog(
			'Only use associated Music Info for Videos from Auto Generated Channels',
		);
	}
}

type FetchResponse<T> = { done: false } | ({ done: true } & T) | null;

function fetchYoutubeChannel(
	channelId: string | null,
): FetchResponse<YoutubeChannelInfo> {
	if (!ytChannelEnabled || typeof channelId !== 'string') {
		return null;
	}
	const cache = youtubeChannelCache[channelId];
	if (cache) {
		if (cache.done && !('error' in cache)) {
			return cache;
		}
		return null;
	}
	console.debug('fetching youtube channel for id', channelId);
	youtubeChannelCache[channelId] = {
		done: false,
	};

	fetch(`https://youtube.com/channel/${channelId}`)
		.then((response) => response.text())
		.then((responseText) => {
			const data = textJsonUtils.findJson(
				responseText,
				'ytInitialData = ',
			);
			console.debug('data =', data);

			const musicArtistName =
				data.metadata?.channelMetadataRenderer?.musicArtistName ?? null;

			youtubeChannelCache[channelId] = {
				done: true,
				musicArtistName,
			};
			console.debug(channelId, '=>', youtubeChannelCache[channelId]);
			Connector.onStateChanged();
		})
		.catch((err) => {
			Util.debugLog(
				`Failed to fetch youtube channel data for ${channelId}: ${err}`,
				'warn',
			);
			youtubeChannelCache[channelId] = {
				done: true,
				error: `${err}`,
			};
		});

	return youtubeChannelCache[channelId];
}

function fetchYoutubeWatch(
	videoId: string | null,
): FetchResponse<YoutubeWatchInfo> {
	if (!ytWatchEnabled || typeof videoId !== 'string') {
		return null;
	}
	const cache = youtubeWatchCache[videoId];
	if (cache) {
		if (cache.done && !('error' in cache)) {
			return cache;
		}
		return null;
	}
	console.debug('fetching youtube watch for id', videoId);
	youtubeWatchCache[videoId] = {
		done: false,
	};

	fetch(`https://youtube.com/watch?v=${videoId}`)
		.then((response) => response.text())
		.then((responseText) => {
			const playerResponse = textJsonUtils.findJson(
				responseText,
				'ytInitialPlayerResponse = ',
			);
			console.debug('playerResponse =', playerResponse);
			// (window as any).playerResponse = playerResponse;
			const data = textJsonUtils.findJson(
				responseText,
				'ytInitialData = ',
			);
			console.debug('data =', data);
			// (window as any).data = data;

			const category = textJsonUtils.getFirst(
				playerResponse,
				'microformat.playerMicroformatRenderer.category',
			);
			/**
			 * @prop {string}   videoId
			 * @prop {string}   title
			 * @prop {string}   lengthSeconds
			 * @prop {string[]} keywords
			 * @prop {string}   channelId
			 * @prop {string}   shortDescription
			 * @prop {string}   author
			 */
			type VideoDetails = {
				videoId: string;
				title: string;
				lengthSeconds: string;
				keywords: string[];
				channelId: string;
				shortDescription: string;
				author: string;
			};
			const videoDetails: VideoDetails = textJsonUtils.getFirst(
				playerResponse,
				'videoDetails',
			);

			const descriptionEngagementPanel = textJsonUtils.getIf(
				data,
				'engagementPanels[].engagementPanelSectionListRenderer',
				(panel) =>
					panel?.targetId ==
					'engagement-panel-structured-description',
			);

			const attributed = textJsonUtils
				.getAll(
					descriptionEngagementPanel,
					'content.structuredDescriptionContentRenderer.items[].horizontalCardListRenderer.cards[].videoAttributeViewModel',
				)
				.map((obj) => {
					const trackArt: string | undefined = textJsonUtils
						.getAll(obj, 'image.sources[].url')
						.at(-1);
					Util.debugLog(trackArt, 'info');
					return {
						trackArt: trackArt
							? /^https?:\/\//.exec(trackArt)
								? trackArt
								: `${window.origin}${trackArt}`
							: undefined,
						track: obj.title,
						artist: obj.subtitle,
						album: textJsonUtils.getFirst(
							obj,
							'secondarySubtitle.content',
						),
					};
				});

			const chapterEngagementPanel = textJsonUtils.getIf(
				data,
				'engagementPanels[].engagementPanelSectionListRenderer',
				(panel) =>
					panel?.targetId ===
					'engagement-panel-macro-markers-description-chapters',
			);
			const chapters = textJsonUtils
				.getAll(chapterEngagementPanel, [
					'content.structuredDescriptionContentRenderer.items[].horizontalCardListRenderer.cards[].macroMarkersListItemRenderer',
					'content.macroMarkersListRenderer.contents[].macroMarkersListItemRenderer',
				])
				.map((obj) => {
					const timeText = textJsonUtils.getIf(
						obj,
						['timeDescription.simpleText', 'timeDescription'],
						(x) => typeof x === 'string',
					);
					const title = textJsonUtils.getIf(
						obj,
						['title.simpleText', 'title'],
						(x) => typeof x === 'string',
					);
					return {
						title,
						time: Util.stringToSeconds(timeText),
					};
				});

			youtubeWatchCache[videoId] = {
				done: true,
				category,

				title: videoDetails.title,
				channel: videoDetails.author,
				channelId: videoDetails.channelId,

				chapters,
				attributedTrackInfo:
					attributed.length > 0 ? attributed[0] : undefined,
			};
			console.debug(videoId, '=>', youtubeWatchCache[videoId]);
			Connector.onStateChanged();
		})
		.catch((err) => {
			Util.debugLog(
				`Failed to fetch youtube video data for ${videoId}: ${err}`,
				'warn',
			);
			youtubeWatchCache[videoId] = {
				done: true,
				error: `${err}`,
			};
		});

	return youtubeWatchCache[videoId];
}

function fetchYoutubeMusic(
	videoId: string | null,
): FetchResponse<YoutubeMusicInfo> {
	if (!ytMusicEnabled || typeof videoId !== 'string') {
		return null;
	}
	const cache = youtubeMusicCache[videoId];
	if (cache) {
		if (cache.done && !('error' in cache)) {
			return cache;
		}
		return null;
	}
	console.debug('fetching youtube music for id', videoId);
	youtubeMusicCache[videoId] = { done: false };

	const body = JSON.stringify({
		context: {
			client: {
				// parameters are needed, you get a 400 if you omit these
				// specific values are just what I got when doing a request
				// using firefox
				clientName: 'WEB_REMIX',
				clientVersion: '1.20221212.01.00',
			},
		},
		captionParams: {},
		videoId,
	});

	fetch('https://music.youtube.com/youtubei/v1/player', {
		method: 'POST',
		headers: {
			'Content-Type': 'application/json',
		},
		body,
	})
		.then((response) => response.json())
		.then((videoInfo) => {
			(window as any).videoInfo = videoInfo;
			const musicVideoType: string | undefined =
				videoInfo.videoDetails?.musicVideoType;

			const recognisedByYtMusic =
				musicVideoType?.startsWith('MUSIC_VIDEO_') || false;
			const currentTrackInfo: { artist?: string; track?: string } = {};

			switch (musicVideoType) {
				// if videoDetails is not MUSIC_VIDEO_TYPE_OMV, it seems like it's
				// not something youtube music actually knows, so it usually gives
				// wrong results, so we only return if it is that musicVideoType
				case 'MUSIC_VIDEO_TYPE_OMV':
					currentTrackInfo.artist = videoInfo.videoDetails.author;
					currentTrackInfo.track = videoInfo.videoDetails.title;
			}

			youtubeMusicCache[videoId] = {
				done: true,
				recognisedByYtMusic,
				currentTrackInfo,
			};
			Connector.onStateChanged();
		})
		.catch((err) => {
			Util.debugLog(
				`Failed to fetch youtube music data for ${videoId}: ${err}`,
				'warn',
			);
			youtubeMusicCache[videoId] = {
				done: true,
				error: `${err}`,
			};
		});

	return youtubeMusicCache[videoId];
}

Connector.isTrackArtDefault = (trackArt) =>
	trackArt ===
	'https://www.gstatic.com/youtube/img/watch/yt_music_channel.jpeg';

function getTrackInfoFromYoutubeFetch():
	| BaseState
	| Record<string, never>
	| undefined {
	const videoId = getVideoId();
	const ytWatchResponse = fetchYoutubeWatch(videoId);

	if (!ytWatchResponse) {
		// disabled or errored
		return;
	}

	if (!ytWatchResponse.done) {
		// still running, lets be patient
		return {};
	}

	// order of importance:
	// 1. chapters (+author)
	// 2. attributed
	// 3. title (+author)
	const hasChapters = ytWatchResponse.chapters?.length !== 0;
	const hasAttributed = !!ytWatchResponse.attributedTrackInfo;

	// short circuit, if the video is attributed and we take any attribution, and there are no chapters, then just return that info
	if (!hasChapters && hasAttributed && !useAttributedOnlyForAutoGenerated) {
		return ytWatchResponse.attributedTrackInfo;
	}

	let channel = ytWatchResponse.channel;
	let generatedChannel = false;

	const ytChannelResult = fetchYoutubeChannel(ytWatchResponse.channelId);
	if (!ytChannelResult) {
		// disabled or errored
		// keep going
	} else {
		if (!ytChannelResult.done) {
			// still running, lets be patient
			return {};
		}
		if (ytChannelResult.musicArtistName) {
			channel = ytChannelResult.musicArtistName;
			generatedChannel = true;
		}
	}

	if (!hasChapters && hasAttributed && generatedChannel) {
		return ytWatchResponse.attributedTrackInfo;
	}

	let title = ytWatchResponse.title;
	// let { artist, track } = Util.processYtVideoTitle(ytWatchResponse.title);

	if (hasChapters) {
		const videoElem = document.querySelector(videoSelector);
		if (!videoElem) {
			console.debug('what time is it????');
			// uhhhh, try again later
			return {};
		}
		let { currentTime, duration, playbackRate } =
			videoElem as HTMLVideoElement;

		// let artistTrack = Util.processYtVideoTitle(
		// 	ytWatchResponse.chapters[0].title,
		// );
		let i = 0;
		do {
			const chapter = ytWatchResponse.chapters[i];
			if (chapter.time > currentTime) {
				// console.debug(chapter.time, '>', currentTime);
				break;
			}
			title = chapter.title;
			// artistTrack = Util.processYtVideoTitle(chapter.title);
			i++;
		} while (i < ytWatchResponse.chapters.length);
		// console.debug('title', title);
		// if (artistTrack.track) {
		// 	track = artistTrack.track;
		// 	if (artistTrack.artist) {
		// 		artist = artistTrack.artist;
		// 	}
		// }
	}

	let artistTrack = Util.processYtVideoTitle(title);

	if (!artistTrack.track) {
		artistTrack.track = title;
	}
	if (!artistTrack.artist) {
		artistTrack.artist = channel;
	}

	return artistTrack;
}

function getTrackInfoFromYoutubeMusic():
	| ArtistTrackInfo
	| Record<string, never>
	| undefined {
	const videoId = getVideoId();
	const ytMusicResponse = fetchYoutubeMusic(videoId);

	if (!ytMusicResponse?.done) {
		// still running, lets be patient
		return {};
	}

	return ytMusicResponse.currentTrackInfo;
}

function getTrackInfoFromChapters() {
	// Short circuit if chapters not available - necessary to avoid misscrobbling with SponsorBlock.
	if (!areChaptersAvailable()) {
		return {
			artist: null,
			track: null,
		};
	}

	const chapterName = Util.getTextFromSelectors(chapterNameSelector);
	const artistTrack = Util.processYtVideoTitle(chapterName);
	if (!artistTrack.track) {
		artistTrack.track = chapterName;
	}
	return artistTrack;
}

function getTrackInfoFromTitle(): ArtistTrackInfo {
	let { artist, track } = Util.processYtVideoTitle(
		Util.getTextFromSelectors(videoTitleSelector),
	);
	if (!artist) {
		artist = Util.getTextFromSelectors(channelNameSelector);
	}

	return { artist, track };
}

function removeLtrRtlChars(text: string) {
	return MetadataFilter.filterWithFilterRules(text, [
		{ source: /\u200e/g, target: '' },
		{ source: /\u200f/g, target: '' },
	]);
}

function removeNumericPrefix(text: string) {
	return MetadataFilter.filterWithFilterRules(text, [
		// `NN.` or `NN)`
		{ source: /^\d{1,2}[.)]\s?/, target: '' },
		/*
		 * `(NN).` Ref: https://www.youtube.com/watch?v=KyabZRQeQgk
		 * NOTE Initial tracklist format is (NN)  dd:dd  Artist - Track
		 * YouTube adds a dot symbol after the numeric prefix.
		 */
		{ source: /^\(\d{1,2}\)\./, target: '' },
	]);
}

function isVideoStartedPlaying() {
	const videoElement = document.querySelector(
		videoSelector,
	) as HTMLVideoElement;
	return videoElement && videoElement.currentTime > 0;
}

function isVideoCategoryAllowed() {
	if (allowedCategories.length === 0) {
		return true;
	}

	const videoCategory = getVideoCategory();
	if (!videoCategory) {
		return false;
	}

	return (
		allowedCategories.includes(videoCategory) ||
		videoCategory === Category.Unknown
	);
}
