export interface YtMusicApi {
	videoDetails?: YtMusicVideoDetails;
	microformat?: microformatDataRenderer;
	// nonexhaustive
	[other: string]: unknown | undefined;
}

interface microformatDataRenderer {
	microformatDataRenderer?: Partial<{
		// track or title
		title: string;
		// channel or "Episode • <podcast>"
		description: string;
		// for ATV album track: [("<artist>",)+ "<album>", "<track>"] (https://www.youtube.com/watch?v=i1D8WkGuq4g)
		// for ATV single: ["<artist>", "<track>"] (https://www.youtube.com/watch?v=tNT5sYheayM)
		// all artists are in the .videoDetails.author string, in this order.
		tags: string[];
		pageOwnerDetails: {
			// channel (if applicable "<channel> - Topic")
			name: string;
			externalChannelId: string;
			youtubeProfileUrl: string;
		};
		// Music or Entertainment or... others
		category: string;
		// nonexhaustive
		[other: string]: unknown;
	}>;
}

// prettier-ignore
type MusicVideoType =
	| 'PRIVATELY_OWNED_TRACK' // YouTube Music Library
	| 'ATV' 				  // Autogenerated Topic Video
	| 'SHOULDER' 			  // ¯\_(ツ)_/¯
	| 'OMV' 				  // Original Music Video
	| 'UGC' 				  // User Generated Content
	| 'OFFICIAL_SOURCE_MUSIC' // Music, but not single Track
	| 'PODCAST_EPISODE' 	  // Podcast
;

type YtMusicVideoDetails = Partial<{
	videoId: string;
	// track or title
	title: string;
	channelId: string;
	// square cover art if ATV, otherwise just thumbnails
	thumbnail: thumbnails;
	lengthSeconds: number;
	// artist(s joined by delimiters), channel or podcast
	author: string;
	musicVideoType?: `MUSIC_VIDEO_TYPE_${MusicVideoType}`;
	// nonexhaustive
	[other: string]: unknown | undefined;
}>;

interface thumbnails {
	thumbnails: {
		url: string;
		width: number;
		height: number;
	}[];
}
