import { State } from '@/core/types';
import type { trackInfoFields } from '../youtube';
import type { YtMusicApi } from './yt-api';

export interface YtApiResult {
	recognisedByYtMusic: boolean;
	currentTrackInfo: Pick<State, (typeof trackInfoFields)[number]>;
	category?: string;
}

interface YtMusicApiArgs {
	videoId: string;
	title: string;
	channel: string;
}

export function keyFn(args: YtMusicApiArgs) {
	return JSON.stringify(args);
}

export async function ytMusicApiRequest({
	videoId,
	title,
	channel,
}: YtMusicApiArgs): Promise<YtApiResult> {
	const body = JSON.stringify({
		context: {
			client: {
				// parameters are needed, you get a 400 if you omit these
				// specific values are just what I got when doing a request
				// using firefox
				clientName: 'WEB_REMIX',
				clientVersion: '1.20221212.01.00',
				// todo: language and region
			},
		},
		captionParams: {},
		videoId,
	});

	const videoInfo: YtMusicApi = await fetch(
		'https://music.youtube.com/youtubei/v1/player',
		{
			method: 'POST',
			headers: {
				'Content-Type': 'application/json',
			},
			body,
		},
	).then((resp) => resp.json());

	const recognisedByYtMusic =
		videoInfo.videoDetails?.musicVideoType?.startsWith(
			'MUSIC_VIDEO_TYPE_',
		) || false;

	const category = videoInfo.microformat?.microformatDataRenderer?.category;

	let artist = null;
	let artists = null;
	let track = null;
	let trackArt = null;
	let isPodcast = false;

	switch (videoInfo.videoDetails?.musicVideoType) {
		/* eslint no-fallthrough: "off" */

		// YouTube Music Library uploads
		// with metadata: "<track>" by "<author>"
		// without metadata: "filename.mp3" by "Music Library Uploads"
		case 'MUSIC_VIDEO_TYPE_PRIVATELY_OWNED_TRACK': // FALLTHROUGH
			// if the author is set as "Music Library Uploads", we ignore it
			// otherwise, accept as valid metadata.
			// it does not appear that this is translated, luckily
			if (videoInfo.videoDetails.author === 'Music Library Uploads') {
				break;
			}

		//* Autogenerated Topic Video
		// good: "<track>" by "<author>" (https://www.youtube.com/watch?v=wPm68ZJqNy8)
		// uploader is always a " - Topic" channel. the " - Topic" part is never added to the author field
		case 'MUSIC_VIDEO_TYPE_ATV': {
			// always good, created from information supplied to google by record labels
			({ author: artist, title: track } = videoInfo.videoDetails);
			const thumbs = videoInfo.videoDetails.thumbnail?.thumbnails;
			// use thumbnail from here, if available.
			const thumbUrl = thumbs?.[thumbs.length - 1].url;
			// and not default (for PRIVATELY_OWNED_TRACK)
			if (!thumbUrl?.includes('cover_track_default')) {
				trackArt = thumbUrl;
			}
			const tags = videoInfo.microformat?.microformatDataRenderer?.tags;
			if (artist && tags) {
				let artistPos = 0;
				artists = [];
				for (const tag of tags) {
					const tagIndex = artist.indexOf(tag, artistPos);
					if (tagIndex < 0) {
						// probably some translated artist name
						continue;
					}

					artists.push(tag);

					artistPos = tagIndex + tag.length;
					if (artistPos === artist.length) {
						break;
					}
				}

				if (artistPos !== artist.length) {
					Util.debugLog(
						`didn't match entire artist '${artist}' with tags '${tags.join(',')}'`,
						'warn',
					);
				}
			}

			break;
		}

		// album preview? music video?
		// good: "On a Cherry Blossom Night" by "あいみょん" (http://youtube.com/watch?v=YXe7GQnvzqY)
		// bad: not found yet?
		case 'MUSIC_VIDEO_TYPE_SHOULDER': // FALLTHROUGH
			// treat like OMV for now
			void 0;

		//* Original Music Video
		// good: "<track>" by "<author>" (https://www.youtube.com/watch?v=GsiQM4aYecE)
		// bad: "<title>" by "<channel>" (https://www.youtube.com/watch?v=sIDRbAUjGvA)
		// bug?: "Pinkie" by "Diversity - All Songs" (https://www.youtube.com/watch?v=yu_XJc_5__Q)
		// uploader (probably) has to be an "Official Artist Channel"
		case 'MUSIC_VIDEO_TYPE_OMV': {
			// may need processing if it's exactly "<title>" by "<channel>" -> don't use those
			// if it's not exactly that, then it should be good.
			// EXCEPT NOT: videos that are part of music playlists seem to have a wrong artist set.

			// <channel> or "Episode • <podcast>"
			// but NEVER "<channel> - Topic"
			// let's abuse this to find out if it's a podcast mislabel without having to localize
			const channelOrEpisode =
				videoInfo.microformat?.microformatDataRenderer?.description;

			if (
				videoInfo.videoDetails.title === title &&
				videoInfo.videoDetails.author === channel
			) {
				// do not use, let title parsing handle it.
			} else if (
				videoInfo.videoDetails.author &&
				videoInfo.videoDetails.author !== channelOrEpisode &&
				channelOrEpisode?.includes(videoInfo.videoDetails.author)
			) {
				// don't use it either here, prevent podcast name from being scrobbled as author
			} else {
				({ author: artist, title: track } = videoInfo.videoDetails);
			}
			break;
		}

		// ! short and simple: the rest don't reliably provide good information.

		//* User Generated Content
		// album: "<title>" by "<channel>" (https://www.youtube.com/watch?v=RXWIitU8V0A)
		case 'MUSIC_VIDEO_TYPE_UGC':
			// similar to OMV, unclear why something is UGC or OMV.
			// it seems though that UGC does not have the title doctored with.
			// "Official Artist Channel"s can also get a video marked as UGC (https://www.youtube.com/watch?v=cMkJDPvJxdk)
			// ignore, let title parsing handle it
			break;

		// Official video content, but not for a single track
		// uploader (probably) has to be an "Official Artist Channel"
		case 'MUSIC_VIDEO_TYPE_OFFICIAL_SOURCE_MUSIC':
			// we will probably never hit here because chapters will parse?
			// in any case this should not carry any information if it's for multiple videos (mix/album)
			break;

		// podcast episodes.
		case 'MUSIC_VIDEO_TYPE_PODCAST_EPISODE':
			// not music, ignore
			isPodcast = true;
			break;

		default:
			if (recognisedByYtMusic) {
				Util.debugLog(
					`YTMusic API: unknown musicVideoType '${videoInfo.videoDetails!.musicVideoType}'. ` +
						'Please tell the web-scrobbler maintainers about it.',
					'warn',
				);
			}
	}

	return {
		recognisedByYtMusic,
		currentTrackInfo: { artist, artists, track, trackArt, isPodcast },
		category,
	};
}
