name: Publish
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  deploy:
    name: Publish release on GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6

      - name: Request website update
        run: |
          curl -X POST \
              -H "Authorization: token ${GH_FA_TOKEN}" \
              -H "Accept: application/vnd.github.everest-preview+json" \
              -d "{\"event_type\":\"${VERSION}\"}" \
              https://api.github.com/repos/${WEBSITE_REPO}/dispatches
        env:
          GH_FA_TOKEN: ${{ secrets.GH_FA_TOKEN }}
          WEBSITE_REPO: web-scrobbler/website-resources
          VERSION: ${{ github.ref_name }}

      - name: Publish release on GitHub
        run: gh release edit "${{ github.ref_name }}" --draft=false
        env:
          GH_TOKEN: ${{ secrets.BOT_PAT }}
          GH_REPO: ${{ github.repository }}
