name: Release Drafter

on:
  pull_request_target:
    types:
      - closed
    branches:
      - master

permissions:
  contents: write

jobs:
  update_release_draft:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v7
