name: Publish
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  deploy:
    name: Publish release on GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Get Node.js version from .nvmrc
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - name: Get the extension version from ref
        run: echo "EXT_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '${{ env.NODE_VERSION }}'

      - name: Install dependencies
        run: npm ci

      - name: Request website update
        run: |
          curl -X POST \
              -H "Authorization: token ${GH_FA_TOKEN}" \
              -H "Accept: application/vnd.github.everest-preview+json" \
              -d "{\"event_type\":\"${VERSION}\"}" \
              https://api.github.com/repos/${WEBSITE_REPO}/dispatches
        env:
          GH_FA_TOKEN: ${{ secrets.GH_FA_TOKEN }}
          WEBSITE_REPO: web-scrobbler/website-resources
          VERSION: ${{ env.EXT_VERSION }}

      - name: Publish release on GitHub
        uses: test-room-7/action-publish-release-drafts@v0
        with:
          github-token: ${{ secrets.BOT_PAT }}
          tag-name: ${{ env.EXT_VERSION }}
